### ISSUE TITLE
1.16.5 doesnt work

### ISSUE THREAD

**Issue by GenericGoose** [SpyMan10/backpackmod-1.16-old#29]
because it's missing [trinkets ](https://www.curseforge.com/minecraft/mc-mods/trinkets) which isn't listed anywhere as a dependency and fabric doesn't tell you to install it either

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'backpackmod'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils$$Lambda$2200/1770090124.apply(Unknown Source)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: dev/emi/trinkets/api/Trinket
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.spyman.backpackmod.common.BackpackMod.onInitialize(BackpackMod.java:33)
	at net.fabricmc.loader.impl.game.minecraft.Hooks$$Lambda$2057/1193164393.accept(Unknown Source)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.ClassNotFoundException: dev.emi.trinkets.api.Trinket
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more

```
adding trinkets made it not crash but it locks up on loading/generating a world

**Comment by GenericGoose** [comment]
tried a different backpack mod and it seems the lock-up is caused by [trinkets itself](https://github.com/emilyploszaj/trinkets/issues/85)

**Comment by SpyMan10** [comment]
Hello, the version you tried to use require trinkets mod, if you needn't trinkets mod use this one : https://www.curseforge.com/minecraft/mc-mods/backpackmod/files/3124432
